name: Continuous Integration by EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  Local_Image:
    runs-on: self-hosted 

    steps:
      - name: Git Pull
        run: cd /home/ec2-user/continuous-integration && git pull

      - name: Build Docker Image
        run: sudo docker build -t local_image:0.1 /home/ec2-user/continuous-integration/app

      - name: List Docker Images
        run: sudo docker images
      
      - name: Run Docker Container
        run: sudo docker run -d --name local_container -p 9002:9001 local_image:0.1

      - name: List Docker Processes
        run: sudo docker ps


# name: Docker Build and Push

# on:
#   push:
#     branches:
#       - main  # Replace with your branch name

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: ./app  # Path to the Dockerfile and build context
#           push: true
#           tags: |
#             yakirbartech/continuous-integration:0.4

#       - name: Logout from Docker Hub
#         run: docker logout

