name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: ls command
        run: ls

      - name: Touch yakir.txt
        run: echo "Hello, Yakir!" > yakir.txt
        
      - name: ls command
        run: ls
  
  pwd:
    runs-on: ubuntu-latest

    steps:
      - name: Print pwd
        run: pwd
